import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className="h-full">
        <main className="bg-slate-100 h-full pt-4">
          <div className="container bg-white px-12 mx-auto max-w-5xl">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
